root = "."
tmp_dir = "tmp/air"

[build]
  bin = "./tmp/air/cackuk"
  cmd = "go build -o ./tmp/air/cackuk cmd/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "docs", "scripts"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "domain", "config", "external", "utils"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true