version: "2.3"

services:
  cakcuk_app:
    build: .
    ports: 
      - 8080:80 
      - 443:443 
    depends_on:
      cakcuk_mysql:
        condition: service_healthy
    environment: 
      - PORT=80
      - MYSQL_HOST=cakcuk_mysql:3306
      - MYSQL_USERNAME=cakcuk_user
      - MYSQL_PASSWORD=cakcuk_password
      - MYSQL_DATABASE=cakcuk_db
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}
      - SLACK_EVENT_ENABLED=true
      - SLACK_RTM_ENABLED=false

  cakcuk_mysql:
    image: mysql:8
    ports: 
      - 33070:3306
    healthcheck:
      test: mysqladmin ping -h localhost
    environment: 
      - MYSQL_ROOT_HOST=cakcuk_mysql
      - MYSQL_USER=cakcuk_user
      - MYSQL_PASSWORD=cakcuk_password
      - MYSQL_DATABASE=cakcuk_db
      - MYSQL_ROOT_PASSWORD=cakcuk_password
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
