name: Build UI

on:
  push:
    paths:
      - "playground-ui/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        node-version: [14.4.0]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build playgound
        run: |
          cd playground-ui
          npm install
          npm run build
      