name: Build GO

on:
  pull_request:
    paths-ignore:
      - "playground-ui/**"
    branches: [master]
  push:
    paths-ignore:
      - "playground-ui/**"
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.14.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
        id: go
      - name: Build Cakcuk Main
        run: go build cmd/main.go
