name: Build UI

on:
  push:
    paths:
      - "playground-ui/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.4.0]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build playgound
        run: |
          cd playground-ui
          npm install
          npm run build
      - name: Generate Static Playground UI
        run: |
          cd playground-ui 
          npm run export
          rm -rf public
          cp -R __sapper__/export public
      - name: Commit generated Playground UI on master
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Muhammad Iskandar Dzulqornain'
          git config --global user.email 'midzulqornain@gmail.com'
          git config advice.addIgnoredFile false
          git remote set-url origin https://isdzulqor:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -f playground-ui/public
          git commit -m "Auto: Generate static site for Cakcuk playground"
          current_branch=`git rev-parse --abbrev-ref HEAD`
          git push origin $current_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 