name: Build UI

on:
  push:
    branches: 
      - 'ui/*'
  pull_request:
    branches: 
      - 'ui/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.4.0]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build playgound
        run: |
          cd playground-ui
          npm install -g yarn
          yarn install
          yarn run build
      - name: Generate Static Playground UI
        run: |
          cd playground-ui 
          yarn run export
          rm -rf public
          cp -R __sapper__/export public
      - name: Commit Playground UI build
        uses: EndBug/add-and-commit@v4.1.0
        with:
          add: 'playground-ui/public'
          author_name: M Iskandar Dzulqornain
          author_email: midzulqornain@gmail.com
          message: "Auto: Build and Commit playground ui"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 