name: Build UI

on:
  push:
    branches: 
      - 'ui'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd playground-ui && npm install
      - run: cd playground-ui && npm run build
        env:
          CI: true
      - name: Committ Playground UI build
        uses: EndBug/add-and-commit@v4.1.0
        with:
          add: 'playground-ui/public'
          author_name: M Iskandar Dzulqornain
          author_email: midzulqornain@gmail.com
          message: "Build and commit playground ui"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 