name: Test Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.test.yaml up -d
        # TODO:
        # add Step for curl check health check until healthy
        # or add step for knowing docker-compose to finished if only containers are healthy
      - name: Set up Go 1.14.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      - name: Test
        run: go test -v ./...