name: Test Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.test.yaml up -d
      - name: Set up Go 1.14.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      - name: Check Cakcuk readiness
        timeout-minutes: 3
        shell: bash
        run: |
          status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost/api/health)
          while [[ "$status_code" -ne 200 ]] ; do
              echo "status code: $status_code. Will sleep for 2 second."
              sleep 2
              echo "Retrying...."
              status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost/api/health)
          done
          echo "Cakcuk is Ready... status code: $status_code"
      - name: Test
        run: go test -v ./...